### PR TITLE
Initial unit test

### PR DESCRIPTION
**Pull request by NyorJa**
* covered api package and did some minor code
     quality

### CODE REVIEW

**Review by rahulkrishnan221 — APPROVED** [review]
Changes looks good to me. Approving

**Comment by rahulkrishnan221** [comment]
Unit test for API covered and code quality improvement. Here removed redundant null check and used StringUtils for doing the same. Moved all constants to one place.

**Comment by NyorJa** [comment]
please add the label also as "hacktoberfest-accepted" thanks

**Comment by NyorJa** [comment]
please close this issue and add "hacktoberfest-accepted" as label.Thanks

**Pull request merged**
